"""
run_75_5120ChaseRed_BATES.py — Blank template for running srm_1d from a .ric file
======================================================================

Generic driver that loads any motor defined by a .ric file (and sibling
``<motor>.transport.yaml``), runs the 1D PISO simulation, and saves
pressure / flow / summary plots. Optionally overlays experimental head-
end pressure from a CSV with a coded-in time-offset alignment knob.

Copy this file to a new name (e.g. ``run_my_motor.py``) and edit the
config block at the top. Do not edit this file in place — keep the
blank version as a reference.

Usage:
    python -m srm_1d.examples.run_template
    # or, after copying / renaming:
    python -m srm_1d.examples.run_my_motor

Outputs (default names; change SAVE_PREFIX below):
    <prefix>_pressure.png   pressure trace (vs experimental if supplied)
    <prefix>_flow.png       flow-field snapshot at FLOW_SNAPSHOT_TIME
    <prefix>_summary.png    4-panel summary

See ``srm_1d/examples/hasegawa_motor_a.py`` for a fully calibrated
example using these same primitives.
"""

from pathlib import Path

import matplotlib
matplotlib.use('Agg')          # non-interactive backend; safe for sweeps
import matplotlib.pyplot as plt

from srm_1d.openmotor_adapter import run_from_ric
from srm_1d.plotting import (
    plot_pressure,
    plot_flow_snapshot,
    plot_summary,
    load_experimental_csv,
)
from srm_1d.run_artifacts import artifact_dir


# =====================================================================
# CONFIG — EDIT THIS BLOCK
# =====================================================================

# ---- Motor definition --------------------------------------------------
# Path to the .ric file. The sibling <motor>.transport.yaml must exist
# next to it (RPA/CEA effective gas transport). Most repo motors ship
# both together under srm_1d/motors/.
MOTOR_PATH = Path(__file__).resolve().parents[1] / 'motors' / '75_5120ChaseRed_BATES.ric'

# Human-readable identifier used in plot titles and output filenames.
MOTOR_LABEL = "75_5120ChaseRed_BATES"
SAVE_PREFIX = "75_5120ChaseRed_BATES"       # output filenames: <prefix>_pressure.png, etc.


# ---- Igniter -----------------------------------------------------------
# Pyrogen YAML name (looked up in srm_1d/motors/ by load_pyrogen) or an
# explicit YAML path. 'bpnv' is the safest high-perf default per the
# feedback_igniter_conventions memory. Sutton sizing kicks in when
# pyrogen_mass / pyrogen_throat_area / pyrogen_volume are None.
PYROGEN = 'bpnv'
PYROGEN_MASS = None            # kg; None → Sutton default m = 0.12 * V_F^0.7
PYROGEN_THROAT_AREA = None     # m^2; None → Sutton default
PYROGEN_VOLUME = None          # m^3; None → Sutton default


# ---- Solver / calibration knobs ---------------------------------------
# Ma 2020 roughness in the Haaland friction factor. Typical: 30–80 µm.
# Hasegawa A v0.7.0 calibrated value: 37.5e-6.
ROUGHNESS = 35.0e-6

# Gnielinski entry/temperature-ratio coefficient. Typical: 0.4–0.5.
# Hasegawa A v0.7.0 calibrated value: 0.429.
KAPPA = 0.45

# Goodman ignition surface temperature [K]. Typical: 700–1000.
# Hasegawa A v0.7.0 calibrated value: 927.
T_IGNITION = 900.0

# Solid-phase thermal conductivity [W/(m·K)]. Material property; for
# AP/HTPB composites typically 0.3–0.5. Calibrated 0.482 for Hasegawa A.
K_SOLID = 0.4

# Termination: head-end pressure below this aborts the run [Pa].
P_CUTOFF = 0.05e6              # 50 kPa — well into tail-off

# Termination: arbitrary time cutoff [s].
TIME_MAX = 5.0

# Adaptive-CFL target. 0.3 is the standard. Lower → safer / slower.
CFL_TARGET = 0.3

# Snapshot cadence (s) for the in-memory flow-field history.
SNAPSHOT_INTERVAL = 0.2

# Status print cadence (s of sim time). 0.0 disables.
PRINT_INTERVAL = 0.2


# ---- Experimental overlay (optional) ----------------------------------
# Set EXPERIMENTAL_CSV_PATH = None to skip the overlay entirely. When
# set, the CSV is loaded via load_experimental_csv and rendered on
# both plot_pressure and plot_summary.
EXPERIMENTAL_CSV_PATH = None
# EXPERIMENTAL_CSV_PATH = Path(__file__).resolve().parents[1] / 'data' / 'my_static_fire.csv'

# CSV column layout — adjust to match your file.
EXPERIMENTAL_TIME_COL = 0
EXPERIMENTAL_PRESSURE_COL = 1
EXPERIMENTAL_DELIMITER = ','
EXPERIMENTAL_SKIP_HEADER = 1
EXPERIMENTAL_PRESSURE_UNIT = 'MPa'   # one of: 'Pa', 'kPa', 'MPa', 'psi'
EXPERIMENTAL_LABEL = "Static fire"

# Time-offset tuning factor [s]. Added to every experimental timestamp
# before plotting. Use to align the experimental ignition event with
# sim t=0. Positive value shifts the experimental trace right; negative
# shifts it left. Iterate by eye until ignition shapes align, then
# freeze the value.
#
# Practical hint: start at 0.0, plot, read the experimental ignition
# time vs sim ignition time off the chart, and set
# EXPERIMENTAL_TIME_OFFSET = (sim_ignition_t) − (exp_ignition_t).
EXPERIMENTAL_TIME_OFFSET = 0.0


# ---- Plot toggles -----------------------------------------------------
FLOW_SNAPSHOT_TIME = 0.2       # plot the flow field at this sim time [s]
SAVE_PLOTS = True              # if False, plt.show() instead of saving


# =====================================================================
# DRIVER — usually no edits below this line
# =====================================================================

def main():
    # ----- Run the simulation ------------------------------------------
    # run_from_ric is the canonical entry point: it loads the .ric +
    # transport.yaml, builds (geometry, propellant, nozzle, pyrogen
    # chamber), and calls run_simulation. Returns (result, perf, nozzle,
    # geometry, propellant).
    print(f"Running {MOTOR_LABEL} from {MOTOR_PATH.name}...")
    result, perf, nozzle, geo, prop = run_from_ric(
        str(MOTOR_PATH),
        pyrogen=PYROGEN,
        pyrogen_mass=PYROGEN_MASS,
        pyrogen_throat_area=PYROGEN_THROAT_AREA,
        pyrogen_volume=PYROGEN_VOLUME,
        roughness=ROUGHNESS,
        kappa=KAPPA,
        T_ignition=T_IGNITION,
        k_solid=K_SOLID,
        P_cutoff=P_CUTOFF,
        t_max=TIME_MAX,
        cfl_target=CFL_TARGET,
        snapshot_interval=SNAPSHOT_INTERVAL,
        print_interval=PRINT_INTERVAL,
    )

    # ----- Optional experimental overlay -------------------------------
    experimental = None
    if EXPERIMENTAL_CSV_PATH is not None:
        experimental = load_experimental_csv(
            str(EXPERIMENTAL_CSV_PATH),
            time_col=EXPERIMENTAL_TIME_COL,
            pressure_col=EXPERIMENTAL_PRESSURE_COL,
            delimiter=EXPERIMENTAL_DELIMITER,
            skip_header=EXPERIMENTAL_SKIP_HEADER,
            pressure_unit=EXPERIMENTAL_PRESSURE_UNIT,
            label=EXPERIMENTAL_LABEL,
        )
        print(
            f"Loaded experimental trace: {EXPERIMENTAL_CSV_PATH.name} "
            f"({len(experimental['time'])} samples)"
        )

    # ----- Plots -------------------------------------------------------
    # Per-run artifact dir: artifacts/<SAVE_PREFIX>/<timestamp>_<sha>[-dirty]/.
    # Reruns don't overwrite earlier outputs (matches run_template.py
    # convention). SAVE_PREFIX is reused as the subdirectory name.
    out = artifact_dir(SAVE_PREFIX) if SAVE_PLOTS else None
    pressure_path = str(out / 'pressure.png') if SAVE_PLOTS else None
    flow_path     = str(out / 'flow.png')     if SAVE_PLOTS else None
    summary_path  = str(out / 'summary.png')  if SAVE_PLOTS else None

    plot_pressure(
        result,
        title=f"{MOTOR_LABEL} — 1D PISO Head-End Pressure",
        experimental=experimental,
        time_offset=EXPERIMENTAL_TIME_OFFSET,
        save_path=pressure_path,
    )

    plot_flow_snapshot(
        result,
        t_target=FLOW_SNAPSHOT_TIME,
        save_path=flow_path,
    )

    plot_summary(
        result, performance=perf,
        experimental=experimental,
        time_offset=EXPERIMENTAL_TIME_OFFSET,
        title=f"{MOTOR_LABEL} — Simulation Summary",
        save_path=summary_path,
    )

    if SAVE_PLOTS:
        plt.close('all')
        print(
            f"\nPlots saved: {pressure_path}, {flow_path}, {summary_path}"
        )
    else:
        plt.show()


if __name__ == '__main__':
    main()
